# Generated by Django 3.2.23 on 2023-12-21 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_people',
            new_name='number_of_guests',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(choices=[(datetime.time(18, 0), '18:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30'), (datetime.time(21, 0), '21:00'), (datetime.time(21, 30), '21:30'), (datetime.time(22, 0), '22:00')]),
        ),
    ]
